import Link from "next/link";
import { FileText, CheckCircle2, Clock, Archive } from "lucide-react";
import { requireUser, canApprove } from "@/lib/dal";
import { db } from "@/lib/db";
import { getServerLocale } from "@/lib/i18n/locale";
import { getDictionary } from "@/lib/i18n/dictionaries";
import Topbar from "@/components/Topbar";
import Card from "@/components/ui/Card";
import KpiTile from "@/components/ui/KpiTile";
import StatusPill from "@/components/ui/StatusPill";
import GenerateReportButton from "./GenerateReportButton";

const TYPE_COLOR: Record<string, string> = { MANAGEMENT: "var(--cat-1)", SPECIAL: "var(--cat-4)", STATUTORY: "var(--cat-2)" };
const TYPE_KEY: Record<string, keyof ReturnType<typeof getDictionary>["m"]> = {
  MANAGEMENT: "reportTypeManagement",
  SPECIAL: "reportTypeSpecial",
  STATUTORY: "reportTypeStatutory",
};
const STATUS_TONE: Record<string, "good" | "warning"> = { GENERATED: "good", GENERATING: "warning", ARCHIVED: "good" };

export default async function ReportPage() {
  const user = await requireUser();
  const locale = await getServerLocale();
  const dict = getDictionary(locale);
  const isZh = locale === "zh" || locale === "zh-Hant";

  const reports = await db.reportDoc.findMany({ where: { organizationId: user.organizationId }, orderBy: { createdAt: "desc" } });
  const generated = reports.filter((r) => r.status === "GENERATED").length;
  const generating = reports.filter((r) => r.status === "GENERATING").length;
  const archived = reports.filter((r) => r.status === "ARCHIVED").length;

  const statusLabel = (s: string) => (s === "GENERATED" ? dict.m.generated : s === "GENERATING" ? dict.m.generating : dict.m.archived);

  // Rows with reportKey set were generated by the system itself (see GenerateReportButton /
  // /api/admin/reports/generate) and are clickable back to a live-recomputed report view.
  // Everything else is still a manual log entry — most report types don't have a generation
  // pipeline yet, so the categories below describe intended use, not a blanket capability.
  function reportHref(r: (typeof reports)[number]): string | null {
    if (!r.periodYear) return null;
    if (r.reportKey === "consolidated_income_statement") return `/report/consolidated?year=${r.periodYear}`;
    if (r.reportKey === "consolidated_balance_sheet") return `/report/consolidated-balance-sheet?year=${r.periodYear}`;
    if (r.reportKey === "consolidated_cash_flow") return `/report/consolidated-cash-flow?year=${r.periodYear}`;
    if (r.reportKey === "ar_aging") return `/report/ar-aging?year=${r.periodYear}`;
    if (r.reportKey === "monthly_risk" && r.periodMonth) return `/report/monthly-risk?year=${r.periodYear}&month=${r.periodMonth}`;
    if (r.reportKey === "audit_report") return `/report/audit-report?year=${r.periodYear}`;
    return null;
  }
  const categories = isZh
    ? [
        ["管理报表", "面向内部经营决策", "利润表、资产负债表、现金流量表、经营简报等 — 由财务人员编制后在此登记备查"],
        ["专项报表", "主题分析", "应收账龄、风险预警月报等 — 服务特定管理场景，同样为人工登记"],
        ["法定报表", "对外披露/审计", "年度合并财务报表 — 经外部审计后在此归档，系统本身不执行审计"],
      ]
    : [
        ["Management Reports", "For internal decisions", "Income statement, balance sheet, cash flow, operating briefs — prepared by finance and logged here for tracking"],
        ["Special Reports", "Topic-based analysis", "AR aging, monthly risk report — for specific management needs, also logged manually"],
        ["Statutory Reports", "External disclosure/audit", "Annual consolidated statements — archived here once externally audited; this system doesn't perform the audit"],
      ];

  return (
    <>
      <Topbar dict={dict} locale={locale} title={dict.nav.report} desc={dict.nav.report} user={user} />
      <div className="mx-auto w-full max-w-[1480px] flex-1 space-y-4 px-[26px] py-5">
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
          <KpiTile icon={FileText} color="var(--cat-1)" label={dict.m.reportCount} value={String(reports.length)} />
          <KpiTile icon={CheckCircle2} color="var(--status-good)" label={dict.m.generated} value={String(generated)} />
          <KpiTile icon={Clock} color="var(--status-warning)" label={dict.m.generating} value={String(generating)} />
          <KpiTile icon={Archive} color="var(--cat-4)" label={dict.m.archived} value={String(archived)} />
        </div>

        {canApprove(user.role) && <GenerateReportButton locale={locale} />}

        <div className="grid gap-4 lg:grid-cols-2">
          <Card title={dict.m.reportListCard}>
            <div className="overflow-x-auto">
              <table className="w-full text-[12.6px]">
                <thead>
                  <tr className="text-left text-[11.3px] font-semibold" style={{ color: "var(--ink-400)" }}>
                    <th className="pb-2">{dict.m.thReportName}</th>
                    <th className="pb-2">{dict.m.thType}</th>
                    <th className="pb-2">{dict.m.thPeriod}</th>
                    <th className="pb-2">{dict.m.thGenTime}</th>
                    <th className="pb-2">{dict.m.thStatus}</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((r) => {
                    const href = reportHref(r);
                    return (
                    <tr key={r.id} className="border-t" style={{ borderColor: "var(--border)" }}>
                      <td className="py-2.5 font-semibold" style={{ color: "var(--ink-900)" }}>
                        {href ? (
                          <Link href={href} className="hover:underline" style={{ color: "var(--cat-1)" }}>
                            {locale === "en" ? r.nameEn : r.nameZh}
                          </Link>
                        ) : (
                          locale === "en" ? r.nameEn : r.nameZh
                        )}
                      </td>
                      <td className="py-2.5">
                        <span
                          className="whitespace-nowrap rounded-full px-2 py-0.5 text-[10.5px] font-bold"
                          style={{ background: `color-mix(in srgb, ${TYPE_COLOR[r.type]} 14%, transparent)`, color: TYPE_COLOR[r.type] }}
                        >
                          {dict.m[TYPE_KEY[r.type]]}
                        </span>
                      </td>
                      <td className="py-2.5" style={{ color: "var(--ink-400)" }}>
                        {r.period}
                      </td>
                      <td className="tabular-nums py-2.5" style={{ color: "var(--ink-400)" }}>
                        {r.generatedAt ? r.generatedAt.toISOString().slice(0, 16).replace("T", " ") : "—"}
                      </td>
                      <td className="py-2.5">
                        <StatusPill tone={STATUS_TONE[r.status]} label={statusLabel(r.status)} />
                      </td>
                    </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </Card>

          <Card title={dict.m.reportCatsCard}>
            <div className="flex flex-col gap-3.5">
              {categories.map(([name, sub, desc]) => (
                <div key={name}>
                  <div className="flex items-baseline justify-between text-[12.5px]">
                    <span className="font-bold" style={{ color: "var(--ink-900)" }}>
                      {name}
                    </span>
                    <span className="font-semibold" style={{ color: "var(--ink-400)" }}>
                      {sub}
                    </span>
                  </div>
                  <div className="mt-1 text-xs" style={{ color: "var(--ink-400)" }}>
                    {desc}
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </div>
    </>
  );
}
