ALTER TABLE "MonthlyFinancial" ADD COLUMN "sellExp" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "MonthlyFinancial" ADD COLUMN "adminExp" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "MonthlyFinancial" ADD COLUMN "rndExp" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "MonthlyFinancial" ADD COLUMN "financeExp" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "MonthlyFinancial" ADD COLUMN "headcount" INTEGER NOT NULL DEFAULT 0;
